services:
  - type: web
    name: service-desk-management-system
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .api/server.js
    envVars:
      - key: NODE_ENV
        value: production
